# Generated by Django 5.1.1 on 2024-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                help_text="дата производства",
                null=True,
                verbose_name="Дата производства",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="creation_date",
            field=models.DateField(
                auto_now_add=True,
                help_text="Введите дату создания",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="last_modified_date",
            field=models.DateField(
                auto_now=True,
                help_text="Введите дату последнего изменения",
                verbose_name="Дата последнего изменения",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="product/image/",
                verbose_name="Фото",
            ),
        ),
    ]
